/**
 * Characters carried over from the local-only build.
 *
 * The password hash keeps the original `sha256$<salt>$<key>` format, so the
 * player signs in with the password they already had — it was never known to
 * anyone but them, and `verifyPassword` upgrades the row to scrypt on the
 * first successful login.
 */

import type { GameProfile } from '../src/game/types';

export type SeedPlayer = {
    id: string;
    email: string;
    nick: string;
    passwordHash: string;
    profile: GameProfile;
};

export const SEED_PLAYERS: SeedPlayer[] = [
    {
        id: '7133e2c9-f10e-407b-bc15-886c1a08ac9a',
        email: 'arek09082001@gmail.com',
        nick: 'arek',
        passwordHash:
            'sha256$1f24d716f23e005f67392406a0175c9d$e00b71f57532f0aa0ee118b4a12fb0dd53b24faded9d3f45551cdc7a32746716',
        profile: {
            id: '7133e2c9-f10e-407b-bc15-886c1a08ac9a',
            nick: 'arek',
            level: 34,
            exp: 893,
            expMax: 17345,
            gold: 2385,
            pa: 200,
            paMax: 200,
            paRegeneratedAt: 1785321753249,
            playedSeconds: 3759,
            lastSeenAt: 1785321753249,
            vitality: 25,
            strength: 35,
            luck: 19,
            vitalityPointsAssigned: 20,
            strengthPointsAssigned: 30,
            luckPointsAssigned: 14,
            attributePoints: 2,
            hp: 620,
            dmgMin: 107,
            dmgMax: 175,
            armor: 78,
            critChance: 29,
            critPower: 230,
            dodge: 11,
            stun: 4,
            monstersKilled: 838,
            uniqueItemsFound: 123,
            heroicItemsFound: 37,
            legendaryItemsFound: 11,
            restTasks: {},
            currentMapId: 3,
            stageProgress: {
                '1_ithan-hunters-cave': 6,
                '1_ithan-yss': 6,
                '2_torneg-mountain-cave': 6,
                '2_torneg-spider-nest': 6,
                '3_karka-virgin-forest': 6,
                '3_karka-zulu-settlement': 6,
            },
            inventory: [
                {
                    id: 'drop_c1fd26ee0c5ef1a7',
                    name: 'Medal',
                    icon: 'items/medal.gif',
                    image: 'items/medal.gif',
                    imageUrl: '/game-assets/items/medal.gif',
                    type: 'talisman',
                    itemType: 'talisman',
                    itemTypeName: 'Talizman',
                    rarity: 'common',
                    rarityName: 'Zwykły',
                    rarityColor: '#ffffff',
                    rarityCss: '',
                    level: 30,
                    stats: { stun: 4 },
                    bonusStats: { stun: { value: 4, name: 'Ogłuszenie', suffix: '%' } },
                    effect: null,
                    effectValue: null,
                    effectData: null,
                    power: 12,
                    price: 12,
                    quantity: 1,
                    stun: 4,
                },
                {
                    id: 'drop_adf819c5435c176c',
                    name: 'Butelka PA',
                    icon: 'items/pa.gif',
                    image: 'items/pa.gif',
                    imageUrl: '/game-assets/items/pa.gif',
                    type: 'potion',
                    itemType: 'potion',
                    itemTypeName: 'Mikstura',
                    rarity: 'common',
                    rarityName: 'Zwykły',
                    rarityColor: '#ffffff',
                    rarityCss: '',
                    level: 30,
                    stats: {},
                    bonusStats: {},
                    effect: 'pa',
                    effectValue: 5,
                    effectData: { type: 'pa', value: 5 },
                    power: 10,
                    price: 10,
                    quantity: 1,
                },
                {
                    id: 'drop_d2245218c93036e5',
                    name: 'Mocny Zbroja płytowa',
                    icon: 'items/plate.gif',
                    image: 'items/plate.gif',
                    imageUrl: '/game-assets/items/plate.gif',
                    type: 'armor',
                    itemType: 'armor',
                    itemTypeName: 'Zbroja',
                    rarity: 'unique',
                    rarityName: 'Unikalny',
                    rarityColor: '#66cc66',
                    rarityCss: 'unique',
                    level: 30,
                    stats: { armor: 59, hp: 83 },
                    bonusStats: { hp: { value: 83, name: 'Punkty życia', suffix: '' } },
                    effect: null,
                    effectValue: null,
                    effectData: null,
                    power: 613,
                    price: 1532,
                    quantity: 1,
                    armor: 59,
                    hp: 83,
                },
                {
                    id: 'drop_25d8866b45e51725',
                    name: 'Zaklęty Młot',
                    icon: 'items/hammer.gif',
                    image: 'items/hammer.gif',
                    imageUrl: '/game-assets/items/hammer.gif',
                    type: 'weapon',
                    itemType: 'weapon',
                    itemTypeName: 'Broń',
                    rarity: 'unique',
                    rarityName: 'Unikalny',
                    rarityColor: '#66cc66',
                    rarityCss: 'unique',
                    level: 30,
                    stats: { dmgMin: 28, dmgMax: 57, critChance: 20 },
                    bonusStats: { critChance: { value: 20, name: 'Szansa krytyka', suffix: '%' } },
                    effect: null,
                    effectValue: null,
                    effectData: null,
                    power: 552,
                    price: 1380,
                    quantity: 1,
                    dmgMin: 28,
                    dmgMax: 57,
                    critChance: 20,
                },
                {
                    id: 'drop_3cea684beb0ea60c',
                    name: 'Butelka PA',
                    icon: 'items/pa.gif',
                    image: 'items/pa.gif',
                    imageUrl: '/game-assets/items/pa.gif',
                    type: 'potion',
                    itemType: 'potion',
                    itemTypeName: 'Mikstura',
                    rarity: 'common',
                    rarityName: 'Zwykły',
                    rarityColor: '#ffffff',
                    rarityCss: '',
                    level: 30,
                    stats: {},
                    bonusStats: {},
                    effect: 'pa',
                    effectValue: 5,
                    effectData: { type: 'pa', value: 5 },
                    power: 10,
                    price: 10,
                    quantity: 1,
                },
                {
                    id: 'drop_16045411999fcc76',
                    name: 'Boski Butelka PA',
                    icon: 'items/pa.gif',
                    image: 'items/pa.gif',
                    imageUrl: '/game-assets/items/pa.gif',
                    type: 'potion',
                    itemType: 'potion',
                    itemTypeName: 'Mikstura',
                    rarity: 'legendary',
                    rarityName: 'Legendarny',
                    rarityColor: '#fa9a20',
                    rarityCss: 'legendary',
                    level: 30,
                    stats: {},
                    bonusStats: {},
                    effect: 'pa',
                    effectValue: 25,
                    effectData: { type: 'pa', value: 25 },
                    power: 50,
                    price: 500,
                    quantity: 1,
                },
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
            ],
            equipped: {
                weapon: {
                    id: '701_417aecf76940',
                    shopItemId: '701',
                    name: 'Kosa Zapomnianego Króla',
                    icon: 'items/spear.gif',
                    image: 'items/spear.gif',
                    imageUrl: '/game-assets/items/spear.gif',
                    type: 'weapon',
                    itemType: 'weapon',
                    itemTypeName: 'Broń',
                    rarity: 'legendary',
                    rarityName: 'Legendarny',
                    rarityColor: '#fa9a20',
                    rarityCss: 'legendary',
                    level: 30,
                    stats: { dmgMin: 90, dmgMax: 140, critChance: 10, critPower: 50, doubleDamage: 10 },
                    bonusStats: {
                        dmgMin: 90,
                        dmgMax: 140,
                        critChance: 10,
                        critPower: 50,
                        doubleDamage: 10,
                    },
                    effect: null,
                    effectValue: null,
                    effectData: null,
                    power: 300,
                    price: 55000,
                    quantity: 1,
                    dmgMin: 90,
                    dmgMax: 140,
                    critChance: 10,
                    critPower: 50,
                    doubleDamage: 10,
                },
                armor: {
                    id: '415_92fa81db589a',
                    shopItemId: '415',
                    name: 'Zbroja Górskiego Klanu',
                    icon: 'items/chainmail.gif',
                    image: 'items/chainmail.gif',
                    imageUrl: '/game-assets/items/chainmail.gif',
                    type: 'armor',
                    itemType: 'armor',
                    itemTypeName: 'Zbroja',
                    rarity: 'heroic',
                    rarityName: 'Heroiczny',
                    rarityColor: '#2090fe',
                    rarityCss: 'heroic',
                    level: 25,
                    stats: { armor: 78, hp: 85, dodge: 6 },
                    bonusStats: { armor: 78, hp: 85, dodge: 6 },
                    effect: null,
                    effectValue: null,
                    effectData: null,
                    power: 169,
                    price: 13000,
                    quantity: 1,
                    armor: 78,
                    hp: 85,
                    dodge: 6,
                },
                accessory: {
                    id: '425_ec005dcec7e4',
                    shopItemId: '425',
                    name: 'Amulet Zaćmienia',
                    icon: 'items/amulet.gif',
                    image: 'items/amulet.gif',
                    imageUrl: '/game-assets/items/amulet.gif',
                    type: 'talisman',
                    itemType: 'talisman',
                    itemTypeName: 'Talizman',
                    rarity: 'legendary',
                    rarityName: 'Legendarny',
                    rarityColor: '#fa9a20',
                    rarityCss: 'legendary',
                    level: 25,
                    stats: { hp: 120, critChance: 8, critPower: 30, stun: 4 },
                    bonusStats: { hp: 120, critChance: 8, critPower: 30, stun: 4 },
                    effect: null,
                    effectValue: null,
                    effectData: null,
                    power: 162,
                    price: 20000,
                    quantity: 1,
                    hp: 120,
                    critChance: 8,
                    critPower: 30,
                    stun: 4,
                },
            },
        },
    },
];
